### ISSUE TITLE
Added ru (русский) translation

### ISSUE THREAD

**Issue by ashed** [d4rken/reddit-android-appstore#82] opened 2017-01-05 15:05 UTC
I have translated your application into `ru` (*русский*). Here is the xml:
```xml
<resources>
    <string name="app_name">/r/Android App store</string>
    <string name="button_refresh">Обновить</string>
    <string name="button_filter">Фильтр</string>
    <string name="button_search">Поиск</string>
    <string name="screen_details">Подробности</string>
    <string name="button_contact">Контакт</string>
    <string name="button_download">Скачать</string>
    <string name="gplay">Google Play</string>
    <string name="fdroid">F-Droid</string>
    <string name="website">Вебсайт</string>
    <string name="mail">E-Mail</string>
    <string name="reddit">Reddit</string>
    <string name="twitter">Twitter</string>
    <string name="instagram">Instagram</string>
    <string name="hint_type_to_filter">Печатать фильтр</string>
    <string name="button_about">О программе</string>
    <string name="text_contributors">Контрибуторы</string>
    <string name="licenses">Лицензии</string>
    <string name="version">Версия</string>
    <string name="bugreport">Отчет об ошибке</string>
    <string name="settings">Настройки</string>
    <string name="more">Больше</string>
    <string name="appearance">Внешний вид</string>
    <string name="preference_theme">Тема</string>
    <string name="preference_theme_desc">Тема для использования</string>
    <string name="restart">Нужен рестарт для смены тем</string>
    <string name="later">Позже</string>
    <string name="app_category_everything">Все</string>
    <string name="error">Ошибка получения репозиториев</string>
    <string name="data_options">Настройки данных</string>
    <string name="screenshots">Скриншоты</string>
    <string name="data_option_loadmedia_title">Иконки &amp; скриншоты</string>
    <string name="data_option_loadmedia_summary">Загрузить иконки и скриншоты</string>
    <string name="update">Обновление доступно</string>
    <string name="update_confirm">Обновить</string>
    <string name="flag">Отметить приложение</string>
    <string name="no_message">Введите сообщение</string>
    <string name="flag_text">Почему вы отметили приложение? Вас перенаправят на reddit, для личного сообщения r/Android mod team</string>
    <plurals name="x_items">
        <item quantity="one">%s item</item>
        <item quantity="other">%s items</item>
    </plurals>
    <string-array name="themes"></string-array>
    <string-array name="themesValues"></string-array>
</resources>

```

---

*Translation made with [Stringlate](https://github.com/LonamiWebs/Stringlate).*

**Comment by d4rken** [comment] 2017-01-05 22:01
Duplicate of #77

**Closed by d4rken** 2017-01-05 22:01 UTC
Labels: enhancement
